[pytest]
DJANGO_SETTINGS_MODULE = configuration.test_settings
# -- recommended but optional:
python_files = test_*.py *_test.py
filterwarnings = ignore::DeprecationWarning
asyncio_mode = auto
addopts = --random-order --cov-branch --cov=src --cov-report=xml --cov-report=html --junitxml=pytest.xml
pythonpath = src
